---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME  }}
      PROJECT_ID: ${{ secrets.PROJECT_ID  }}
      GCLOUD_SERVICE_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY  }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses:  google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch

    - name: Configure Docker Client
      run: |-
        echo "$GCLOUD_SERVICE_KEY" > ${HOME}/.docker/gcloud-service-key.json
        gcloud auth activate-service-account --key-file ${HOME}/.docker/gcloud-service-key.json
        gcloud auth configure-docker
  
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG:  ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        kubectl set image deployment/automated-nginx automated-nginx=${{ secrets.IMAGE  }}
   